config/routes.rb
Rails.application.routes.draw do
  root to: "application#home"
  
  get '/dashboard', to: 'application#dashboard', as: :dashboard
  get '/company_registration', to: 'application#company_registration', as: :company_registration
  get '/check', to: 'application#check', as: :check
  
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  
  resources :users, path: '/users'
  
  put '/users/:id/activate/',	to: 'users#activate', as: :activate_user
  put '/users/:id/deactivate/',	to: 'users#deactivate', as: :deactivate_user
  get '/admins',	to: 'users#admins', as: :admins
  
  resources :companies, path: '/company'
  resources :entries, path: '/entry'
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to  :company
  has_many    :entries
  rolify
  # Include default devise modules. Others available are:
  # :registerable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :confirmable, :recoverable,
         :rememberable, :trackable, :validatable
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :activate, :deactivate, :destroy]
  load_and_authorize_resource

  # GET /users
  def index
    @users = User.with_role(:employee)
  end
  
  # GET /admins
  def admins
    @users = User.with_role(:admin)
  end

  # GET /users/new
  def new
    @user = User.new
  end
  
  # GET /users/1
  def show
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  def update
    respond_to do |format|
      if @user.update(User_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PUT /users/1/activate
  def activate
    respond_to do |format|
      if @user.is_active
        format.html { redirect_to @user, notice: 'User is already active.' }
        format.json { render :show, status: :ok, location: @user }
      else
        if @user.update(is_active: true)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end
  
  # PATCH/PUT /users/1/deactivate
  def deactivate
    respond_to do |format|
      if !@user.is_active
        format.html { redirect_to @user, notice: 'User is already deactive.' }
        format.json { render :show, status: :ok, location: @user }
      else
        if @user.update(is_active: false)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /users/1
  def destroy
    #@user.destroy
    respond_to do |format|
      format.html { redirect_to Users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:User).permit(:is_active, :names, :lastnames, :identification, :identification_type, :birth_date, :balance)
    end
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :is_active %>
    <%= f.check_box :is_active %>
  </div>

  <div class="field">
    <%= f.label :identification %>
    <%= f.text_field :identification %>
  </div>

  <div class="field">
    <%= f.label :identification_type %>
    <%= f.number_field :identification_type %>
  </div>

  <div class="field">
    <%= f.label :birth_date %>
    <%= f.date_select :birth_date %>
  </div>

  <div class="field">
    <%= f.label :balance %>
    <%= f.text_field :balance %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/admins.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'New admin', new_user_path %>

<br></br>

<table id="admins-list" class="datatable striped" class="display" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Active</th>
      <th>Names</th>
      <!--<th>Lastnames</th>-->
      <th>Identification</th>
      <!--<th>Identification type</th>-->
      <th>Birth date</th>
      <!--<th>Balance</th>-->
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><i class="material-icons"><%= user.is_active ? "check" : "close" %></i></td>
        <td><%= user.names + " " + user.lastnames %></td>
        <!--<td><%= user.lastnames %></td>-->
        <td><%= user.identification %></td>
        <!--<td><%= user.identification_type %></td>-->
        <td><%= user.birth_date.strftime("%b %e, %Y") %></td>
        <!--<td><%= user.balance %></td>-->
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td>
          <% if user.is_active %>
            <%= link_to 'Deactivate', deactivate_user_path(user), method: :put %>
          <% else %>
            <%= link_to 'Activate', activate_user_path(user), method: :put %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
  
  <tfoot>
    <tr>
      <th>Active</th>
      <th>Names</th>
      <!--<th>Lastnames</th>-->
      <th>Identification</th>
      <!--<th>Identification type</th>-->
      <th>Birth date</th>
      <!--<th>Balance</th>-->
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </tfoot>
</table>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %> | 
<%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'New user', new_user_path %>

<br></br>

<table id="list-users" class="datatable striped" class="display" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Active</th>
      <th>Names</th>
      <!--<th>Lastnames</th>-->
      <th>Identification</th>
      <!--<th>Identification type</th>-->
      <th>Birth date</th>
      <!--<th>Balance</th>-->
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><i class="material-icons"><%= user.is_active ? "check" : "close" %></i></td>
        <td><%= user.names + " " + user.lastnames %></td>
        <!--<td><%= user.lastnames %></td>-->
        <td><%= user.identification %></td>
        <!--<td><%= user.identification_type %></td>-->
        <td><%= user.birth_date.strftime("%b %e, %Y") %></td>
        <!--<td><%= user.balance %></td>-->
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td>
          <% if user.is_active %>
            <%= link_to 'Deactivate', deactivate_user_path(user), method: :put %>
          <% else %>
            <%= link_to 'Activate', activate_user_path(user), method: :put %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
  
  <tfoot>
    <tr>
      <th>Active</th>
      <th>Names</th>
      <!--<th>Lastnames</th>-->
      <th>Identification</th>
      <!--<th>Identification type</th>-->
      <th>Birth date</th>
      <!--<th>Balance</th>-->
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </tfoot>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Is active:</strong>
  <%= @user.is_active %>
</p>

<p>
  <strong>Identification:</strong>
  <%= @user.identification %>
</p>

<p>
  <strong>Identification type:</strong>
  <%= @user.identification_type %>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @user.birth_date %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @user.balance %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>