config/routes.rb
Rails.application.routes.draw do
  root to: "application#home"
  
  get '/dashboard', to: 'application#dashboard', as: :dashboard
  get '/company_registration', to: 'application#company_registration', as: :company_registration
  get '/check', to: 'application#check', as: :check
  
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  
  resources :users, path: '/users'
  
  put '/users/:id/activate/',	to: 'users#activate', as: :activate_user
  put '/users/:id/deactivate/',	to: 'users#deactivate', as: :deactivate_user
  get '/admins',	to: 'users#admins', as: :admins
  
  resources :companies, path: '/company'
  resources :entries, path: '/entry'
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, :only  => :dashboard
  before_action :non_authenticate_user!, :only  => [:home, :company_registration]
  #load_and_authorize_resource except: [:home, :company_registration, :dashboard, :check]
  
  def home
    
  end
  
  def company_registration
    
  end

  def dashboard
      
  end
  
  def check
    #@company = Company.friendly.find(params[:slug])
    #logger.debug "============"
    #logger.debug "============"
    #logger.debug params[:slug]
    #logger.debug "Company attributes hash: #{@company.inspect}"
    #logger.debug "============"
    #logger.debug "============"
  end
  
  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden }
      format.html { redirect_to root_url, :alert => exception.message }
    end
  end
  
  private
  
    # Overwriting the sign_out redirect path method
    def after_sign_out_path_for(resource_or_scope)
      new_user_session_path
    end
  
  protected
    def non_authenticate_user!
      if user_signed_in?
        redirect_to dashboard_url
      end
    end
    
    def authenticate_user!
      unless user_signed_in?
        redirect_to new_user_session_path, :notice => 'You have to log in first'
      else
        super
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
  def title(page_title)
    content_for :title, page_title.to_s
  end
  
  def page_center
    content_for :html_class, "page-center"
    content_for :body_class, "page-center"
  end
end

app/views/application/_footer.html.erb
<footer class="page-footer">
	<div class="footer-copyright">
		<div class="container">
			<span>Copyright © 2015 <a class="grey-text text-lighten-4" href="http://themeforest.net/user/geekslabs/portfolio?ref=geekslabs" target="_blank">GeeksLabs</a> All rights reserved.</span>
			<span class="right"> Design and Developed by <a class="grey-text text-lighten-4" href="http://geekslabs.com/">GeeksLabs</a></span>
		</div>
	</div>
</footer>

app/views/application/_header.html.erb
<!-- START HEADER -->
<header id="header" class="page-topbar">
	<!-- start header nav-->
	<div class="navbar-fixed">
		<nav class="cyan">
			<div class="nav-wrapper">
				<h1 class="logo-wrapper">
					<%= link_to dashboard_url, class: "brand-logo darken-1" do %>
						<%= image_tag "logo.png", alt: "", class: "logo" %>
					<% end %>
					<span class="logo-text">Ponto</span>
				</h1>
				<ul class="right hide-on-med-and-down">
					<li>
						<a href="javascript:void(0);" class="waves-effect waves-block waves-light toggle-fullscreen"><i class="material-icons">settings_overscan</i></a>
					</li>
					<li>
						<a href="javascript:void(0);" class="waves-effect waves-block waves-light"><i class="material-icons">notifications</i></a>
					</li>
					<!-- Dropdown Trigger -->                        
					<li>
						<a href="#" data-activates="chat-out" class="waves-effect waves-block waves-light chat-collapse"><i class="material-icons">chat</i></a>
					</li>
				</ul>
			</div>
		</nav>
	</div>
	<!-- end header nav-->
</header>
<!-- END HEADER -->

app/views/application/_left_sidebar_nav.html.erb
<!-- START LEFT SIDEBAR NAV-->
<aside id="left-sidebar-nav">
	<ul id="slide-out" class="side-nav fixed leftside-navigation">
		<li class="user-details cyan darken-2">
			<div class="row">
				<div class="col s4">
					<%= image_tag "default-avatar.jpg", alt: "", class: "circle responsive-img valign profile-image" %>
				</div>
				<div class="col s8">
					<ul id="profile-dropdown" class="dropdown-content">
						<li>
							<%= link_to "#" do %>
								<i class="material-icons">perm_identity</i>Account
							<% end %>
						</li>
						<li>
							<%= link_to "#" do %>
								<i class="material-icons">settings</i>Settings
							<% end %>
						</li>
						<li class="divider"></li>
						<li>
							<%= link_to destroy_user_session_path, :method => :delete do %>
								<i class="material-icons">keyboard_tab</i>Logout
							<% end %>
						</li>
					</ul>
					<%= link_to "#", class: "btn-flat dropdown-button waves-effect waves-light white-text profile-btn", data: { activates: "profile-dropdown" } do %>
						Santiago<i class="material-icons right">arrow_drop_down</i>
					<% end %>
					<p class="user-roal">Administrador</p>
				</div>
			</div>
		</li>
		
		<li class="no-padding">
			<ul class="collapsible collapsible-accordion">
				<li>
					<%= link_to dashboard_url do %>
						<i class="material-icons">dashboard</i>Dashboard
					<% end %>
				</li>
				
				<li>
					<%= link_to "#", class: "collapsible-header waves-effect waves-cyan" do %>
						<i class="material-icons">domain</i>Company
					<% end %>
					<div class="collapsible-body">
						<ul>
							<li>
								<%= link_to company_path(current_user.company) do %>
									<i class="material-icons">remove_red_eye</i>See
								<% end %>
							</li>
							<li>
								<%= link_to "#" do %>
									<i class="material-icons">mode_edit</i>Edit
								<% end %>
							</li>
						</ul>
					</div>
				</li>
				
				<li>
					<%= link_to "#", class: "collapsible-header waves-effect waves-cyan" do %>
						<i class="material-icons">group</i>Employees
					<% end %>
					<div class="collapsible-body">
						<ul>
							<li>
								<%= link_to users_path do %>
									<i class="material-icons">list</i>List
								<% end %>
							</li>
							<li>
								<%= link_to new_user_path do %>
									<i class="material-icons">person_add</i>Add new
								<% end %>
							</li>
						</ul>
					</div>
				</li>
				
				<li>
					<%= link_to "#", class: "collapsible-header waves-effect waves-cyan" do %>
						<i class="material-icons">contacts</i>Admins
					<% end %>
					<div class="collapsible-body">
						<ul>
							<li>
								<%= link_to admins_path do %>
									<i class="material-icons">list</i>List
								<% end %>
							</li>
							<li>
								<%= link_to new_user_path do %>
									<i class="material-icons">person_add</i>Add new
								<% end %>
							</li>
						</ul>
					</div>
				</li>
				
				<li>
					<%= link_to "#", class: "collapsible-header waves-effect waves-cyan" do %>
						<i class="material-icons">pie_chart</i>Reports
					<% end %>
					<div class="collapsible-body">
						<ul>
							<li>
								<%= link_to "#" do %>
									<i class="material-icons">hourglass_empty</i>Hours
								<% end %>
							</li>
							<li>
								<%= link_to "#" do %>
									<i class="material-icons">today</i>Birthdays
								<% end %>
							</li>
						</ul>
					</div>
				</li>
			</ul>
		</li>

	</ul>
	<%= link_to "#", class: "sidebar-collapse btn-floating btn-medium waves-effect waves-light hide-on-large-only darken-2", data: { activates: "slide-out" } do %>
		<i class="material-icons">menu</i>
	<% end %>
</aside>
<!-- END LEFT SIDEBAR NAV-->

app/views/application/_right_sidebar_nav.html.erb
<!-- START RIGHT SIDEBAR NAV-->
<aside id="right-sidebar-nav">
	<ul id="chat-out" class="side-nav rightside-navigation">
		<li class="li-hover">
			<a href="javascript:void(0);" data-activates="chat-out" class="chat-close-collapse"><i class="material-icons">close</i></a>
			<div class="row margin">
				<form class="col s12">
					<div class="row">
						<div class="input-field margin">
							<i class="material-icons prefix">search</i>
							<input id="icon_prefix" type="text" class="validate" />
							<label for="icon_prefix">Search</label>
						</div>
					</div>
				</form>
			</div>
		</li>
		<li class="li-hover">
			<ul class="chat-collapsible" data-collapsible="expandable">
				<li>
					<div class="collapsible-header teal white-text active"><i class="material-icons">whatshot</i>Recent Activity</div>
					<div class="collapsible-body recent-activity">
						<div class="recent-activity-list chat-out-list row">
							<div class="col s3 recent-activity-list-icon"><i class="material-icons">add_shopping_cart</i></div>
							<div class="col s9 recent-activity-list-text">
								<a href="#">just now</a>
								<p>Jim Doe Purchased new equipments for zonal office.</p>
							</div>
						</div>
						<div class="recent-activity-list chat-out-list row">
							<div class="col s3 recent-activity-list-icon"><i class="material-icons">airplanemode_active</i></div>
							<div class="col s9 recent-activity-list-text">
								<a href="#">Yesterday</a>
								<p>Your Next flight for USA will be on 15th August 2015.</p>
							</div>
						</div>
						<div class="recent-activity-list chat-out-list row">
							<div class="col s3 recent-activity-list-icon"><i class="material-icons">settings_voice</i></div>
							<div class="col s9 recent-activity-list-text">
								<a href="#">5 Days Ago</a>
								<p>Natalya Parker Send you a voice mail for next conference.</p>
							</div>
						</div>
						<div class="recent-activity-list chat-out-list row">
							<div class="col s3 recent-activity-list-icon"><i class="material-icons">store</i></div>
							<div class="col s9 recent-activity-list-text">
								<a href="#">Last Week</a>
								<p>Jessy Jay open a new store at S.G Road.</p>
							</div>
						</div>
						<div class="recent-activity-list chat-out-list row">
							<div class="col s3 recent-activity-list-icon"><i class="material-icons">settings_voice</i></div>
							<div class="col s9 recent-activity-list-text">
								<a href="#">5 Days Ago</a>
								<p>Natalya Parker Send you a voice mail for next conference.</p>
							</div>
						</div>
					</div>
				</li>
				<li>
					<div class="collapsible-header light-blue white-text active"><i class="material-icons">attach_money</i>Sales Report</div>
					<div class="collapsible-body sales-repoart">
						<div class="sales-repoart-list  chat-out-list row">
							<div class="col s8">Target Salse</div>
							<div class="col s4"><span id="sales-line-1"></span></div>
						</div>
						<div class="sales-repoart-list chat-out-list row">
							<div class="col s8">Payment Due</div>
							<div class="col s4"><span id="sales-bar-1"></span></div>
						</div>
						<div class="sales-repoart-list chat-out-list row">
							<div class="col s8">Total Delivery</div>
							<div class="col s4"><span id="sales-line-2"></span></div>
						</div>
						<div class="sales-repoart-list chat-out-list row">
							<div class="col s8">Total Progress</div>
							<div class="col s4"><span id="sales-bar-2"></span></div>
						</div>
					</div>
				</li>
				<li>
					<div class="collapsible-header red white-text"><i class="material-icons">stars</i>Favorite Associates</div>
					<div class="collapsible-body favorite-associates">
						<div class="favorite-associate-list chat-out-list row">
							<div class="col s4">
								<%= image_tag "default-avatar.jpg", alt: "", class: "circle responsive-img online-user valign profile-image" %>
							</div>
							<div class="col s8">
								<p>Eileen Sideways</p>
								<p class="place">Los Angeles, CA</p>
							</div>
						</div>
						<div class="favorite-associate-list chat-out-list row">
							<div class="col s4">
								<%= image_tag "default-avatar.jpg", alt: "", class: "circle responsive-img online-user valign profile-image" %>
							</div>
							<div class="col s8">
								<p>Zaham Sindil</p>
								<p class="place">San Francisco, CA</p>
							</div>
						</div>
						<div class="favorite-associate-list chat-out-list row">
							<div class="col s4">
								<%= image_tag "default-avatar.jpg", alt: "", class: "circle responsive-img offline-user valign profile-image" %>
							</div>
							<div class="col s8">
								<p>Renov Leongal</p>
								<p class="place">Cebu City, Philippines</p>
							</div>
						</div>
						<div class="favorite-associate-list chat-out-list row">
							<div class="col s4">
								<%= image_tag "default-avatar.jpg", alt: "", class: "circle responsive-img online-user valign profile-image" %>
							</div>
							<div class="col s8">
								<p>Weno Carasbong</p>
								<p>Tokyo, Japan</p>
							</div>
						</div>
						<div class="favorite-associate-list chat-out-list row">
							<div class="col s4">
					  			<%= image_tag "default-avatar.jpg", alt: "", class: "circle responsive-img offline-user valign profile-image" %>
							</div>
							<div class="col s8">
								<p>Nusja Nawancali</p>
								<p class="place">Bangkok, Thailand</p>
							</div>
						</div>
					</div>
				</li>
			</ul>
		</li>
	</ul>
</aside>
<!-- END RIGHT SIDEBAR NAV-->

app/views/application/check.html.erb
<% page_center %>

<div class="col s12 z-depth-4 card-panel">
    
    <%= form_tag('/url', html: { class: "form-card"}) do -%>
  
        <div class="row margin">
            <div class="input-field col s12 center">
                <%= image_tag "form-card-logo.png", alt: "", class: "circle responsive-img valign form-card-logo" %>
                <h1 class="center form-card-title">Check</h1>
            </div>
        </div>
        
        <%= render "devise/shared/messages" %>
        
        <div class="row margin">
            <div class="input-field col s12">
                <i class="material-icons prefix">vpn_key</i>
                <%= text_field_tag :identification, nil, required: "required", aria: {required: true}, class: "validate" %>
                <%= label_tag :identification %>
            </div>
        </div>

        <div class="row margin">
            <div class="input-field col s12">
                <i class="material-icons prefix">lock_outline</i>
                <%= password_field_tag :password, nil, required: "required", aria: {required: true}, class: "validate" %>
                <%= label_tag :password %>
            </div>
        </div>
        
        <div class="row">
            <div class="input-field col s12">
                <%= submit_tag "Save", class: "btn waves-effect waves-light col s12" %>
            </div>
        </div>
        
        <div class="row margin">
            <div class="live-date"></div>
            <div class="live-time"></div>
        </div>
        
    <% end %>
</div>

app/views/application/company_registration.html.erb
<% page_center %>

<div class="col s12 z-depth-4 card-panel">
    
    <%= form_tag('/url', html: { class: "form-card"}) do -%>
  
        <div class="row margin">
            <div class="input-field col s12 center">
                <%= image_tag "form-card-logo.png", alt: "", class: "circle responsive-img valign form-card-logo" %>
                <h1 class="center form-card-title">New Company</h1>
            </div>
        </div>
        
        <%= render "devise/shared/messages" %>
        
        <div class="row margin">
            <div class="input-field col s6">
                <%= text_field_tag :business_name, nil, required: "required", aria: {required: true}, class: "validate" %>
                <%= label_tag :business_name %>
            </div>
            <div class="input-field col s6">
                <%= text_field_tag :comercial_name, nil, required: "required", aria: {required: true}, class: "validate" %>
                <%= label_tag :comercial_name %>
            </div>
        </div>
        
        <div class="row margin">
            <div class="input-field col s6">
                <%= text_field_tag :identification, nil, required: "required", aria: {required: true}, class: "validate" %>
                <%= label_tag :identification %>
            </div>
            <div class="input-field col s6">
                <%= text_field_tag :address, nil, required: "required", aria: {required: true}, class: "validate" %>
                <%= label_tag :address %>
            </div>
        </div>

        <div class="row margin">
            <div class="input-field col s6">
                <%= text_field_tag :city, nil, required: "required", aria: {required: true}, class: "validate" %>
                <%= label_tag :city %>
            </div>
            <div class="input-field col s6">
                <%= text_field_tag :state, nil, required: "required", aria: {required: true}, class: "validate" %>
                <%= label_tag :state %>
            </div>
        </div>
        
        <div class="row margin">
            <div class="input-field col s6">
                <%= email_field_tag :email, nil, required: "required", aria: {required: true}, class: "validate" %>
                <%= label_tag :email %>
            </div>
            <div class="input-field col s6">
                <%= password_field_tag :password, nil, required: "required", aria: {required: true}, class: "validate" %>
                <%= label_tag :password %>
            </div>
        </div>
        
        <div class="row margin">
            <div class="input-field col s6">
                <%= text_field_tag :user_identification, nil, required: "required", aria: {required: true}, class: "validate" %>
                <%= label_tag :user_identification %>
            </div>
            <div class="input-field col s6">
                <%= date_field_tag :birth_date, nil, required: "required", aria: {required: true}, class: "datepicker validate" %>
                <%= label_tag :birth_date %>
            </div>
        </div>
        
        
        <div class="row">
            <div class="input-field col s12">
                <%= submit_tag "Save", class: "btn waves-effect waves-light col s12" %>
            </div>
        </div>
        
        
    
    <% end %>
</div>

app/views/application/dashboard.html.erb
<% title "Dashboard" %>

app/views/application/home.html.erb
<% title "Home" %>

app/views/application/index.html.erb
<% title "Home" %>